stages:
  - deploy

image: docker:latest
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:dind

.before_script_template:
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY " | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_IP_SERVER  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy-dev:
  stage: deploy
  extends: .before_script_template
  tags:
    - vmogroup
  script:
    - ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_SERVER "cd /home/vmo/du12_cv_tool_backend && git pull && docker-compose -f docker-compose.dev.yml up --build -d"
  only:
    - dev
