# Generated by Django 4.2.11 on 2024-09-08 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function_name', models.CharField(max_length=255)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('average_time', models.FloatField(default=0.0)),
                ('errors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'metrics_collection',
            },
        ),
    ]
